const items = [
  {
    _id: "0",
    executor: "",
    operatorsComment: "",
    status: "new",
    created: "сегодня 15.00",
    takenToWork: "",
    completed: "",
    description: "Сломалась сушилка для рук",
    branch: "К1",
    author: "Кривопалов С.Е.",
    priority: 4,
    photoUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3xfdw-2iHpnNVvbeTQSC8gOpkasvbT8TXCg&usqp=CAU",
  },
  {
    _id: "1",
    executor: "",
    operatorsComment: "",
    status: "new",
    created: "сегодня 12.00",
    takenToWork: "",
    completed: "",
    description: "Расшатался стол в обеденном зале",
    branch: "К1",
    author: "Кривопалов С.Е.",
    priority: 3,
    photoUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEFpgCcqLtdPfOEUbwkQE_-qUMrnck2ekDJA&usqp=CAU",
  },
  {
    _id: "2",
    executor: "",
    operatorsComment: "",
    status: "new",
    created: "сегодня 10.00",
    takenToWork: "",
    completed: "",
    description: "Шумит вытяжка на кухне",
    branch: "К1",
    author: "Кривопалов С.Е.",
    priority: 1,
    photoUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAtAmzJismbYaxBVruNGxo9vK6Ux7QXY9OBw&usqp=CAU",
  },
  {
    _id: "3",
    executor: "",
    operatorsComment: "",
    status: "new",
    created: "вчера 18.30",
    takenToWork: "",
    completed: "",
    description: "Телевизор в обеденном зале не ловит каналы",
    branch: "К1",
    author: "Кривопалов С.Е.",
    priority: 2,
    photoUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQSxwMHKBelCPWMZN3CzT80eIVks7Mll8rig&usqp=CAU",
  },
  {
    _id: "4",
    status: "work",
    executor: "Владимир Рукосуев",
    completed: "",
    operatorsComment: "Постарайся не залить пол",
    created: "25.09.2022 11.40",
    takenToWork: "15 мин назад",
    description: "Протекает кран в уборной",
    branch: "К2",
    author: "Иванов И.И.",
    priority: 4,
    photoUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuaPWFUW2dwBq3RaY2nh-wv4q7Km8j3Xgnyg&usqp=CAU",
  },
  {
    _id: "5",
    status: "done",
    executor: "Сергей Ковшов",
    operatorsComment:
      "Возьми деньги у администратора, и сходи в леруа мерлен за клеем",
    created: "25.09.2022 11.40",
    takenToWork: "15 мин назад",
    completed: "18.00 20.09.2022",
    description: "В офисе отклеелись обои",
    branch: "К3",
    author: "Петров И.И.",
    priority: 4,
    photoUrl:
      "https://pokleykaoboev.pro/wp-content/uploads/2015/11/otkleivayutsya-oboi-ot-syeny-na-stykah.jpg",
    photoUrlWorkComplete:
      "https://m.vseinstrumenti.ru/uploads/Image/Article%20Images/TB1F1x_FVXXXXXZaXXXXXXXXXXX_!!0-item_pic.jpg",
  },
  {
    _id: "6",
    status: "closed",
    executor: "Сергей Ковшов",
    operatorsComment: "",
    created: "25.09.2022 11.40",
    takenToWork: "20.00 15.09.2022",
    completed: "19.00 20.09.2022",
    description: "Починить выключатель в кладовке",
    branch: "К2",
    author: "Иванов И.И.",
    priority: 2,
    photoUrl:
      "https://thumbs.dreamstime.com/b/%D0%BA%D0%BB%D0%B0%D0%B4%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8%D0%BB%D0%B8-%D0%BA%D0%BB%D0%B0%D0%B4%D0%BE%D0%B2%D0%B0%D1%8F-%D1%81-%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D1%8B%D0%BC%D0%B8-%D0%BB%D0%B0%D0%BC%D0%BF%D0%BE%D0%B9-%D0%B8-%D1%81%D0%B2%D0%B5%D1%82%D0%BE%D0%BC-%D1%88%D0%B0%D1%80%D0%B8%D0%BA-%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D0%B2%D0%B5%D1%82%D0%B0-104499432.jpg",
    photoUrlWorkComplete:
      "https://st.hzcdn.com/fimgs/46a256230ed539cf_2272-w240-h320-b0-p0--.jpg",
  },
];

export default items;
